// ---- stage 2 carrier facts (docs/DESIGN.md 21.9): the parametrised translated types of cart.ml ----
// finite_image A: the literal subtype {x :e omega | x IN 1..dimindex(:A)} is the native index set idx A.
Theorem hl_ty_finite_image_native : forall A:set, A <> Empty -> hl_ty_finite_image A = idx A.
let A. assume HA.
claim Hn1: hl_NUMERAL (hl_BIT1 hl_zero) :e omega. { rewrite hl_one_numeral. exact (nat_p_omega 1 nat_1). }
claim Hd: hl_dimindex A (hl_UNIV A) :e omega. { exact (setexp_ap (2 :^: A) omega (hl_dimindex A) (hl_dimindex_in A HA) (hl_UNIV A) (hl_UNIV_in A HA)). }
claim Hns: hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_dimindex A (hl_UNIV A)) :e 2 :^: omega.
{ exact (setexp_ap omega (2 :^: omega) (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero))) (setexp_ap omega (2 :^: omega :^: omega) hl_numseg hl_numseg_in (hl_NUMERAL (hl_BIT1 hl_zero)) Hn1) (hl_dimindex A (hl_UNIV A)) Hd). }
claim Hdim: hl_dimindex A (hl_UNIV A) = dimindex A. { exact (hl_dimindex_compat A HA (hl_UNIV A) (hl_UNIV_in A HA)). }
claim Hpw: forall x :e omega, (fun r :e omega => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_dimindex A (hl_UNIV A)))) x = 1 <-> 1 <= x /\ x <= dimindex A.
{ let x. assume Hx.
  claim H1: hl_IN omega x (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_dimindex A (hl_UNIV A))) = 1 <-> x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_dimindex A (hl_UNIV A))).
  { exact (hl_IN_compat omega omega_nonempty x Hx (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_dimindex A (hl_UNIV A))) Hns). }
  claim H2: x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_dimindex A (hl_UNIV A))) <-> 1 <= x /\ x <= dimindex A.
  { rewrite (hl_numseg_compat (hl_NUMERAL (hl_BIT1 hl_zero)) Hn1 (hl_dimindex A (hl_UNIV A)) Hd). rewrite hl_one_numeral. rewrite Hdim. apply iffI.
    - assume H. exact (SepE2 omega (fun i => 1 <= i /\ i <= dimindex A) x H).
    - assume H. exact (SepI omega (fun i => 1 <= i /\ i <= dimindex A) x Hx H). }
  exact (iff_eq1_l ((fun r :e omega => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_dimindex A (hl_UNIV A)))) x) (hl_IN omega x (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_dimindex A (hl_UNIV A)))) (beta omega (fun r => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_dimindex A (hl_UNIV A)))) x Hx) (1 <= x /\ x <= dimindex A) (iff_trans (hl_IN omega x (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_dimindex A (hl_UNIV A))) = 1) (x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_dimindex A (hl_UNIV A)))) (1 <= x /\ x <= dimindex A) H1 H2)). }
exact (Sep_ext_iff omega (fun x => (fun r :e omega => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_dimindex A (hl_UNIV A)))) x = 1) (fun x => 1 <= x /\ x <= dimindex A) Hpw).
Qed.
Theorem hl_ty_finite_image_native_nonempty : forall A:set, A <> Empty -> idx A <> Empty.
let A. assume HA. exact (nonempty_of_In (idx A) 1 (SepI omega (fun i => 1 <= i /\ i <= dimindex A) 1 (nat_p_omega 1 nat_1) (andI (1 <= 1) (1 <= dimindex A) (SNoLe_ref 1) (dimindex_ge_1 A HA)))).
Qed.
Theorem hl_ty_finite_image_nonempty : forall A:set, A <> Empty -> hl_ty_finite_image A <> Empty.
let A. assume HA. exact ((eq_sym_i (hl_ty_finite_image A) (idx A) (hl_ty_finite_image_native A HA)) (fun u v => u <> Empty) (hl_ty_finite_image_native_nonempty A HA)).
Qed.
// cart A B: the literal subtype of A :^: hl_ty_finite_image B with the true predicate is the native A :^: idx B.
Theorem hl_ty_cart_native : forall A B:set, A <> Empty -> B <> Empty -> hl_ty_cart A B = A :^: idx B.
let A B. assume HA HB.
prove {x :e A :^: hl_ty_finite_image B | (fun r :e A :^: hl_ty_finite_image B => if True then 1 else 0) x = 1} = A :^: idx B.
rewrite (hl_ty_finite_image_native B HB).
apply set_ext.
- let x. assume Hx. exact (SepE1 (A :^: idx B) (fun x => (fun r :e A :^: idx B => if True then 1 else 0) x = 1) x Hx).
- let x. assume Hx. apply (SepI (A :^: idx B) (fun x => (fun r :e A :^: idx B => if True then 1 else 0) x = 1) x Hx).
  rewrite (beta (A :^: idx B) (fun r => if True then 1 else 0) x Hx). exact (If_i_1 True 1 0 (fun p:prop => fun H:p => H)).
Qed.
Theorem hl_ty_cart_native_nonempty : forall A B:set, A <> Empty -> B <> Empty -> A :^: idx B <> Empty.
let A B. assume HA HB. exact (setexp_nonempty (idx B) A HA).
Qed.
Theorem hl_ty_cart_nonempty : forall A B:set, A <> Empty -> B <> Empty -> hl_ty_cart A B <> Empty.
let A B. assume HA HB. exact ((eq_sym_i (hl_ty_cart A B) (A :^: idx B) (hl_ty_cart_native A B HA HB)) (fun u v => u <> Empty) (hl_ty_cart_native_nonempty A B HA HB)).
Qed.
// finite_sum A B: the literal subtype {x :e omega | x IN 1..dimindex(:A)+dimindex(:B)} is idx_n (dimindex A + dimindex B).
Theorem hl_ty_finite_sum_native : forall A B:set, A <> Empty -> B <> Empty -> hl_ty_finite_sum A B = idx_n (dimindex A + dimindex B).
let A B. assume HA HB.
claim Hn1: (hl_NUMERAL (hl_BIT1 hl_zero)) :e omega. { rewrite hl_one_numeral. exact (nat_p_omega 1 nat_1). }
claim HdA: hl_dimindex A (hl_UNIV A) :e omega. { exact (setexp_ap (2 :^: A) omega (hl_dimindex A) (hl_dimindex_in A HA) (hl_UNIV A) (hl_UNIV_in A HA)). }
claim HdB: hl_dimindex B (hl_UNIV B) :e omega. { exact (setexp_ap (2 :^: B) omega (hl_dimindex B) (hl_dimindex_in B HB) (hl_UNIV B) (hl_UNIV_in B HB)). }
claim Hd: (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) :e omega. { rewrite (hl_add_compat (hl_dimindex A (hl_UNIV A)) HdA (hl_dimindex B (hl_UNIV B)) HdB). exact (add_SNo_In_omega (hl_dimindex A (hl_UNIV A)) HdA (hl_dimindex B (hl_UNIV B)) HdB). }
claim Hns: (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) :e 2 :^: omega.
{ exact (setexp_ap omega (2 :^: omega) (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero))) (setexp_ap omega (2 :^: omega :^: omega) hl_numseg hl_numseg_in (hl_NUMERAL (hl_BIT1 hl_zero)) Hn1) (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) Hd). }
claim Hdim: (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) = dimindex A + dimindex B.
{ rewrite (hl_add_compat (hl_dimindex A (hl_UNIV A)) HdA (hl_dimindex B (hl_UNIV B)) HdB). rewrite (hl_dimindex_compat A HA (hl_UNIV A) (hl_UNIV_in A HA)). rewrite (hl_dimindex_compat B HB (hl_UNIV B) (hl_UNIV_in B HB)). exact (fun q H => H). }
claim Hpw: forall x :e omega, (fun r :e omega => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) x = 1 <-> 1 <= x /\ x <= dimindex A + dimindex B.
{ let x. assume Hx.
  claim H1: hl_IN omega x (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) = 1 <-> x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))).
  { exact (hl_IN_compat omega omega_nonempty x Hx (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) Hns). }
  claim H2: x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) <-> 1 <= x /\ x <= dimindex A + dimindex B.
  { rewrite (hl_numseg_compat (hl_NUMERAL (hl_BIT1 hl_zero)) Hn1 (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) Hd). rewrite hl_one_numeral. rewrite Hdim. apply iffI.
    - assume H. exact (SepE2 omega (fun i => 1 <= i /\ i <= dimindex A + dimindex B) x H).
    - assume H. exact (SepI omega (fun i => 1 <= i /\ i <= dimindex A + dimindex B) x Hx H). }
  exact (iff_eq1_l ((fun r :e omega => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) x) (hl_IN omega x (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) (beta omega (fun r => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) x Hx) (1 <= x /\ x <= dimindex A + dimindex B) (iff_trans (hl_IN omega x (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) = 1) (x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) (1 <= x /\ x <= dimindex A + dimindex B) H1 H2)). }
exact (Sep_ext_iff omega (fun x => (fun r :e omega => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_add (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) x = 1) (fun x => 1 <= x /\ x <= dimindex A + dimindex B) Hpw).
Qed.
Theorem hl_ty_finite_sum_native_nonempty : forall A B:set, A <> Empty -> B <> Empty -> idx_n (dimindex A + dimindex B) <> Empty.
let A B. assume HA HB.
claim HSA: SNo (dimindex A). { exact (omega_SNo (dimindex A) (dimindex_omega A)). }
claim HSB: SNo (dimindex B). { exact (omega_SNo (dimindex B) (dimindex_omega B)). }
claim Hle: dimindex A <= dimindex A + dimindex B.
{ claim H0: dimindex A + 0 <= dimindex A + dimindex B. { exact (add_SNo_Le2 (dimindex A) 0 (dimindex B) HSA SNo_0 HSB (omega_nonneg (dimindex B) (dimindex_omega B))). }
   exact ((add_SNo_0R (dimindex A) HSA) (fun u v => u <= dimindex A + dimindex B) H0). }
claim H1: 1 <= dimindex A + dimindex B. { exact (SNoLe_tra 1 (dimindex A) (dimindex A + dimindex B) SNo_1 HSA (SNo_add_SNo (dimindex A) (dimindex B) HSA HSB) (dimindex_ge_1 A HA) Hle). }
exact (nonempty_of_In (idx_n (dimindex A + dimindex B)) 1 (SepI omega (fun i => 1 <= i /\ i <= dimindex A + dimindex B) 1 (nat_p_omega 1 nat_1) (andI (1 <= 1) (1 <= dimindex A + dimindex B) (SNoLe_ref 1) H1))).
Qed.
Theorem hl_ty_finite_sum_nonempty : forall A B:set, A <> Empty -> B <> Empty -> hl_ty_finite_sum A B <> Empty.
let A B. assume HA HB. exact ((eq_sym_i (hl_ty_finite_sum A B) (idx_n (dimindex A + dimindex B)) (hl_ty_finite_sum_native A B HA HB)) (fun u v => u <> Empty) (hl_ty_finite_sum_native_nonempty A B HA HB)).
Qed.
// finite_prod A B: the literal subtype {x :e omega | x IN 1..dimindex(:A)*dimindex(:B)} is idx_n (dimindex A * dimindex B).
Theorem hl_ty_finite_prod_native : forall A B:set, A <> Empty -> B <> Empty -> hl_ty_finite_prod A B = idx_n (dimindex A * dimindex B).
let A B. assume HA HB.
claim Hn1: (hl_NUMERAL (hl_BIT1 hl_zero)) :e omega. { exact ((eq_sym_i (hl_NUMERAL (hl_BIT1 hl_zero)) 1 hl_one_numeral) (fun u v => u :e omega) (nat_p_omega 1 nat_1)). }
claim HdA: (hl_dimindex A (hl_UNIV A)) :e omega. { exact (setexp_ap (2 :^: A) omega (hl_dimindex A) (hl_dimindex_in A HA) (hl_UNIV A) (hl_UNIV_in A HA)). }
claim HdB: (hl_dimindex B (hl_UNIV B)) :e omega. { exact (setexp_ap (2 :^: B) omega (hl_dimindex B) (hl_dimindex_in B HB) (hl_UNIV B) (hl_UNIV_in B HB)). }
claim Hd: (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) :e omega. { exact ((hl_mul_compat (hl_dimindex A (hl_UNIV A)) HdA (hl_dimindex B (hl_UNIV B)) HdB) (fun u v => v :e omega) (mul_SNo_In_omega (hl_dimindex A (hl_UNIV A)) HdA (hl_dimindex B (hl_UNIV B)) HdB)). }
claim Hns: (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) :e 2 :^: omega.
{ exact (setexp_ap omega (2 :^: omega) (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero))) (setexp_ap omega (2 :^: omega :^: omega) hl_numseg hl_numseg_in (hl_NUMERAL (hl_BIT1 hl_zero)) Hn1) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) Hd). }
claim Hdim: (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) = dimindex A * dimindex B.
{ exact (eq_trans_i (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) ((hl_dimindex A (hl_UNIV A)) * (hl_dimindex B (hl_UNIV B))) (dimindex A * dimindex B) (hl_mul_compat (hl_dimindex A (hl_UNIV A)) HdA (hl_dimindex B (hl_UNIV B)) HdB) (f_equal2 (fun u v => u * v) (hl_dimindex A (hl_UNIV A)) (dimindex A) (hl_dimindex B (hl_UNIV B)) (dimindex B) (hl_dimindex_compat A HA (hl_UNIV A) (hl_UNIV_in A HA)) (hl_dimindex_compat B HB (hl_UNIV B) (hl_UNIV_in B HB)))). }
claim Hpw: forall x :e omega, (fun r :e omega => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) x = 1 <-> 1 <= x /\ x <= dimindex A * dimindex B.
{ let x. assume Hx.
  claim H1: hl_IN omega x (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) = 1 <-> x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))).
  { exact (hl_IN_compat omega omega_nonempty x Hx (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) Hns). }
  claim H2: x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) <-> 1 <= x /\ x <= dimindex A * dimindex B.
  { claim H2a: x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) <-> x :e {i :e omega | (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))}. { exact (iffI (x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) (x :e {i :e omega | (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))}) (fun H => (hl_numseg_compat (hl_NUMERAL (hl_BIT1 hl_zero)) Hn1 (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) Hd) (fun u v => x :e u) H) (fun H => (eq_sym_i (hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) {i :e omega | (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))} (hl_numseg_compat (hl_NUMERAL (hl_BIT1 hl_zero)) Hn1 (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) Hd)) (fun u v => x :e u) H)). }
     claim H2b: x :e {i :e omega | (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))} <-> (hl_NUMERAL (hl_BIT1 hl_zero)) <= x /\ x <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))).
     { apply iffI.
       - assume H. exact (SepE2 omega (fun i => (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) x H).
       - assume H. exact (SepI omega (fun i => (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) x Hx H). }
     claim H2c: ((hl_NUMERAL (hl_BIT1 hl_zero)) <= x /\ x <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) <-> (1 <= x /\ x <= dimindex A * dimindex B).
     { exact (iffI ((hl_NUMERAL (hl_BIT1 hl_zero)) <= x /\ x <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) (1 <= x /\ x <= dimindex A * dimindex B) (fun H => (Hdim) (fun u v => 1 <= x /\ x <= u) ((hl_one_numeral) (fun u v => u <= x /\ x <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) H)) (fun H => (eq_sym_i (hl_NUMERAL (hl_BIT1 hl_zero)) 1 hl_one_numeral) (fun u v => u <= x /\ x <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) ((eq_sym_i (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (dimindex A * dimindex B) Hdim) (fun u v => 1 <= x /\ x <= u) H))). }
     exact (iff_trans (x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) (x :e {i :e omega | (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))}) (1 <= x /\ x <= dimindex A * dimindex B) H2a (iff_trans (x :e {i :e omega | (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))}) ((hl_NUMERAL (hl_BIT1 hl_zero)) <= x /\ x <= (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) (1 <= x /\ x <= dimindex A * dimindex B) H2b H2c)). }
  exact (iff_eq1_l ((fun r :e omega => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) x) (hl_IN omega x (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) (beta omega (fun r => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) x Hx) (1 <= x /\ x <= dimindex A * dimindex B) (iff_trans (hl_IN omega x (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) = 1) (x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) (1 <= x /\ x <= dimindex A * dimindex B) H1 H2)). }
exact (Sep_ext_iff omega (fun x => (fun r :e omega => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_mul (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))))) x = 1) (fun x => 1 <= x /\ x <= dimindex A * dimindex B) Hpw).
Qed.
Theorem hl_ty_finite_prod_native_nonempty : forall A B:set, A <> Empty -> B <> Empty -> idx_n (dimindex A * dimindex B) <> Empty.
let A B. assume HA HB.
claim HSA: SNo (dimindex A). { exact (omega_SNo (dimindex A) (dimindex_omega A)). }
claim HSB: SNo (dimindex B). { exact (omega_SNo (dimindex B) (dimindex_omega B)). }
claim H11: 1 * 1 <= dimindex A * dimindex B. { exact (nonneg_mul_SNo_Le2 1 1 (dimindex A) (dimindex B) SNo_1 SNo_1 HSA HSB (omega_nonneg 1 (nat_p_omega 1 nat_1)) (omega_nonneg 1 (nat_p_omega 1 nat_1)) (dimindex_ge_1 A HA) (dimindex_ge_1 B HB)). }
claim H1: 1 <= dimindex A * dimindex B. { exact ((mul_SNo_oneL 1 SNo_1) (fun u v => u <= dimindex A * dimindex B) H11). }
exact (nonempty_of_In (idx_n (dimindex A * dimindex B)) 1 (SepI omega (fun i => 1 <= i /\ i <= dimindex A * dimindex B) 1 (nat_p_omega 1 nat_1) (andI (1 <= 1) (1 <= dimindex A * dimindex B) (SNoLe_ref 1) H1))).
Qed.
Theorem hl_ty_finite_prod_nonempty : forall A B:set, A <> Empty -> B <> Empty -> hl_ty_finite_prod A B <> Empty.
let A B. assume HA HB. exact ((eq_sym_i (hl_ty_finite_prod A B) (idx_n (dimindex A * dimindex B)) (hl_ty_finite_prod_native A B HA HB)) (fun u v => u <> Empty) (hl_ty_finite_prod_native_nonempty A B HA HB)).
Qed.
// finite_diff A B: the literal subtype {x :e omega | x IN 1..(if dimindex B < dimindex A then dimindex A - dimindex B else 1)}.
Theorem hl_ty_finite_diff_native : forall A B:set, A <> Empty -> B <> Empty -> hl_ty_finite_diff A B = idx_n (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1).
let A B. assume HA HB.
claim Hn1: (hl_NUMERAL (hl_BIT1 hl_zero)) :e omega. { exact ((eq_sym_i (hl_NUMERAL (hl_BIT1 hl_zero)) 1 hl_one_numeral) (fun u v => u :e omega) (nat_p_omega 1 nat_1)). }
claim HdA: (hl_dimindex A (hl_UNIV A)) :e omega. { exact (setexp_ap (2 :^: A) omega (hl_dimindex A) (hl_dimindex_in A HA) (hl_UNIV A) (hl_UNIV_in A HA)). }
claim HdB: (hl_dimindex B (hl_UNIV B)) :e omega. { exact (setexp_ap (2 :^: B) omega (hl_dimindex B) (hl_dimindex_in B HB) (hl_UNIV B) (hl_UNIV_in B HB)). }
claim HdimA: (hl_dimindex A (hl_UNIV A)) = dimindex A. { exact (hl_dimindex_compat A HA (hl_UNIV A) (hl_UNIV_in A HA)). }
claim HdimB: (hl_dimindex B (hl_UNIV B)) = dimindex B. { exact (hl_dimindex_compat B HB (hl_UNIV B) (hl_UNIV_in B HB)). }
claim Hlt2: hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A)) :e 2. { exact (setexp_ap omega 2 (hl_lt (hl_dimindex B (hl_UNIV B))) (setexp_ap omega (2 :^: omega) hl_lt hl_lt_in (hl_dimindex B (hl_UNIV B)) HdB) (hl_dimindex A (hl_UNIV A)) HdA). }
claim Hsubo: hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)) :e omega. { exact (setexp_ap omega omega (hl_sub (hl_dimindex A (hl_UNIV A))) (setexp_ap omega (omega :^: omega) hl_sub hl_sub_in (hl_dimindex A (hl_UNIV A)) HdA) (hl_dimindex B (hl_UNIV B)) HdB). }
claim Hd: (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))) :e omega. { exact (setexp_ap omega omega (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B)))) (setexp_ap omega (omega :^: omega) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A)))) (setexp_ap 2 (omega :^: omega :^: omega) (hl_COND omega) (hl_COND_in omega omega_nonempty) (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) Hlt2) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) Hsubo) (hl_NUMERAL (hl_BIT1 hl_zero)) Hn1). }
claim Hns: (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))) :e 2 :^: omega.
{ exact (setexp_ap omega (2 :^: omega) (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero))) (setexp_ap omega (2 :^: omega :^: omega) hl_numseg hl_numseg_in (hl_NUMERAL (hl_BIT1 hl_zero)) Hn1) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))) Hd). }
claim Hiff: hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A)) = 1 <-> dimindex B < dimindex A.
{ exact (iff_trans (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A)) = 1) ((hl_dimindex B (hl_UNIV B)) < (hl_dimindex A (hl_UNIV A))) (dimindex B < dimindex A) (hl_lt_compat (hl_dimindex B (hl_UNIV B)) HdB (hl_dimindex A (hl_UNIV A)) HdA) (iffI ((hl_dimindex B (hl_UNIV B)) < (hl_dimindex A (hl_UNIV A))) (dimindex B < dimindex A) (fun H => HdimA (fun u v => dimindex B < u) (HdimB (fun u v => u < (hl_dimindex A (hl_UNIV A))) H)) (fun H => (eq_sym_i (hl_dimindex B (hl_UNIV B)) (dimindex B) HdimB) (fun u v => u < (hl_dimindex A (hl_UNIV A))) ((eq_sym_i (hl_dimindex A (hl_UNIV A)) (dimindex A) HdimA) (fun u v => dimindex B < u) H)))). }
claim Hdim: (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))) = (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1).
{ exact (hl_COND_if_dep omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) Hlt2 (dimindex B < dimindex A) Hiff (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) Hsubo (hl_NUMERAL (hl_BIT1 hl_zero)) Hn1 (minus_nat (dimindex A) (dimindex B)) 1 (fun _ => eq_trans_i (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (minus_nat (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (minus_nat (dimindex A) (dimindex B)) (hl_sub_compat (hl_dimindex A (hl_UNIV A)) HdA (hl_dimindex B (hl_UNIV B)) HdB) (f_equal2 (fun u v => minus_nat u v) (hl_dimindex A (hl_UNIV A)) (dimindex A) (hl_dimindex B (hl_UNIV B)) (dimindex B) HdimA HdimB)) (fun _ => hl_one_numeral)). }
claim Hpw: forall x :e omega, (fun r :e omega => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))))) x = 1 <-> 1 <= x /\ x <= (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1).
{ let x. assume Hx.
  claim H1: hl_IN omega x (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))) = 1 <-> x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))).
  { exact (hl_IN_compat omega omega_nonempty x Hx (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))) Hns). }
  claim H2: x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))) <-> 1 <= x /\ x <= (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1).
  { claim H2a: x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))) <-> x :e {i :e omega | (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))}. { exact (iffI (x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))))) (x :e {i :e omega | (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))}) (fun H => (hl_numseg_compat (hl_NUMERAL (hl_BIT1 hl_zero)) Hn1 (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))) Hd) (fun u v => x :e u) H) (fun H => (eq_sym_i (hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))))) {i :e omega | (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))} (hl_numseg_compat (hl_NUMERAL (hl_BIT1 hl_zero)) Hn1 (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))) Hd)) (fun u v => x :e u) H)). }
     claim H2b: x :e {i :e omega | (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))} <-> (hl_NUMERAL (hl_BIT1 hl_zero)) <= x /\ x <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))).
     { apply iffI.
       - assume H. exact (SepE2 omega (fun i => (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))) x H).
       - assume H. exact (SepI omega (fun i => (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))) x Hx H). }
     claim H2c: ((hl_NUMERAL (hl_BIT1 hl_zero)) <= x /\ x <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))) <-> (1 <= x /\ x <= (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1)).
     { exact (iffI ((hl_NUMERAL (hl_BIT1 hl_zero)) <= x /\ x <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))) (1 <= x /\ x <= (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1)) (fun H => (Hdim) (fun u v => 1 <= x /\ x <= u) ((hl_one_numeral) (fun u v => u <= x /\ x <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))) H)) (fun H => (eq_sym_i (hl_NUMERAL (hl_BIT1 hl_zero)) 1 hl_one_numeral) (fun u v => u <= x /\ x <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))) ((eq_sym_i (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))) (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1) Hdim) (fun u v => 1 <= x /\ x <= u) H))). }
     exact (iff_trans (x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))))) (x :e {i :e omega | (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))}) (1 <= x /\ x <= (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1)) H2a (iff_trans (x :e {i :e omega | (hl_NUMERAL (hl_BIT1 hl_zero)) <= i /\ i <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))}) ((hl_NUMERAL (hl_BIT1 hl_zero)) <= x /\ x <= (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))) (1 <= x /\ x <= (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1)) H2b H2c)). }
  exact (iff_eq1_l ((fun r :e omega => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))))) x) (hl_IN omega x (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))))) (beta omega (fun r => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))))) x Hx) (1 <= x /\ x <= (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1)) (iff_trans (hl_IN omega x (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero)))) = 1) (x :e hl_rep omega (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))))) (1 <= x /\ x <= (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1)) H1 H2)). }
exact (Sep_ext_iff omega (fun x => (fun r :e omega => hl_IN omega r (hl_numseg (hl_NUMERAL (hl_BIT1 hl_zero)) (hl_COND omega (hl_lt (hl_dimindex B (hl_UNIV B)) (hl_dimindex A (hl_UNIV A))) (hl_sub (hl_dimindex A (hl_UNIV A)) (hl_dimindex B (hl_UNIV B))) (hl_NUMERAL (hl_BIT1 hl_zero))))) x = 1) (fun x => 1 <= x /\ x <= (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1)) Hpw).
Qed.
Theorem hl_ty_finite_diff_native_nonempty : forall A B:set, A <> Empty -> B <> Empty -> idx_n (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1) <> Empty.
let A B. assume HA HB.
claim HSA: SNo (dimindex A). { exact (omega_SNo (dimindex A) (dimindex_omega A)). }
claim HSB: SNo (dimindex B). { exact (omega_SNo (dimindex B) (dimindex_omega B)). }
claim H1: 1 <= (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1).
{ apply (xm (dimindex B < dimindex A)).
  - assume Hlt.
    claim Hmem: dimindex B :e dimindex A. { exact (ordinal_SNoLt_In (dimindex B) (dimindex A) (nat_p_ordinal (dimindex B) (omega_nat_p (dimindex B) (dimindex_omega B))) (nat_p_ordinal (dimindex A) (omega_nat_p (dimindex A) (dimindex_omega A))) Hlt). }
    claim Hsucc: ordsucc (dimindex B) <= dimindex A. { exact (ordinal_Subq_SNoLe (ordsucc (dimindex B)) (dimindex A) (ordinal_ordsucc (dimindex B) (nat_p_ordinal (dimindex B) (omega_nat_p (dimindex B) (dimindex_omega B)))) (nat_p_ordinal (dimindex A) (omega_nat_p (dimindex A) (dimindex_omega A))) (ordinal_ordsucc_In_Subq (dimindex A) (nat_p_ordinal (dimindex A) (omega_nat_p (dimindex A) (dimindex_omega A))) (dimindex B) Hmem)). }
    claim Hs1: dimindex B + 1 <= dimindex A. { exact ((eq_sym_i (dimindex B + 1) (ordsucc (dimindex B)) (add_SNo_1_ordsucc (dimindex B) (dimindex_omega B))) (fun u v => u <= dimindex A) Hsucc). }
    claim H1s: 1 + dimindex B <= dimindex A. { exact ((add_SNo_com (dimindex B) 1 HSB SNo_1) (fun u v => u <= dimindex A) Hs1). }
    claim Hmn: minus_nat (dimindex A) (dimindex B) = dimindex A + - dimindex B. { exact (If_i_1 (dimindex B <= dimindex A) (dimindex A + - dimindex B) 0 (SNoLtLe (dimindex B) (dimindex A) Hlt)). }
    claim Hlo: 1 <= dimindex A + - dimindex B. { exact (add_SNo_minus_Le2b (dimindex A) (dimindex B) 1 HSA HSB SNo_1 H1s). }
    claim Hlo2: 1 <= minus_nat (dimindex A) (dimindex B). { exact ((eq_sym_i (minus_nat (dimindex A) (dimindex B)) (dimindex A + - dimindex B) Hmn) (fun u v => 1 <= u) Hlo). }
    exact ((eq_sym_i (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1) (minus_nat (dimindex A) (dimindex B)) (If_i_1 (dimindex B < dimindex A) (minus_nat (dimindex A) (dimindex B)) 1 Hlt)) (fun u v => 1 <= u) Hlo2).
  - assume Hn. exact ((eq_sym_i (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1) 1 (If_i_0 (dimindex B < dimindex A) (minus_nat (dimindex A) (dimindex B)) 1 Hn)) (fun u v => 1 <= u) (SNoLe_ref 1)). }
exact (nonempty_of_In (idx_n (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1)) 1 (SepI omega (fun i => 1 <= i /\ i <= (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1)) 1 (nat_p_omega 1 nat_1) (andI (1 <= 1) (1 <= (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1)) (SNoLe_ref 1) H1))).
Qed.
Theorem hl_ty_finite_diff_nonempty : forall A B:set, A <> Empty -> B <> Empty -> hl_ty_finite_diff A B <> Empty.
let A B. assume HA HB. exact ((eq_sym_i (hl_ty_finite_diff A B) (idx_n (if dimindex B < dimindex A then minus_nat (dimindex A) (dimindex B) else 1)) (hl_ty_finite_diff_native A B HA HB)) (fun u v => u <> Empty) (hl_ty_finite_diff_native_nonempty A B HA HB)).
Qed.
